### ISSUE TITLE
update policyList in `roles` section without refereshing the page

### ISSUE THREAD

**Issue by alikhan866** [alikhan866/Casbin-Role-Mgt-Dashboard-RBAC#1]
Right now the scenario is that whenever i add a new policy in the `Policy` tab it adds it to the `database` , However we only fetch the  data once when app is loaded from the database

The issue is that in `Roles.js` `listOfAvailablePolices` contains the outdated data from the database and not the latest data

There should be a state managed and updated according to `onRowAdd` , `onRowUpdate` and `onRowDelete` so that correct data is fetched in `Roles` page without refreshing the React App

**Comment by viveknandhangelella** [comment]
you can use socket.io or graphql subscriptions.

**Comment by alikhan866** [comment]
@viveknandhangelella can you send a PR of the same ?

**Comment by alikhan866** [comment]
Fixed this issue in the latest commit
